[settings]
watch_path = "~/Downloads"

[formats.'3d']
format = "3d"
output_path = "~/EAGLE/libraries"

[formats.'eagle']
format = "eagle"
output_path = "~/EAGLE/libraries"

[profile]
username = ""
password = ""
